- demo/public/index.html
Less hassle than filing an issue.
> Put a title on the demo

- package.json
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer-base.js
I had flattened the array for the input to the shader but overrode it while resolving the merge conflict
> Fix bad merge

- demo/src/App.js
- src/index.js
- src/layers/microscopy-viewer-layer/data-utils/tiff-utils.js
- src/layers/microscopy-viewer-layer/data-utils/zarr-utils.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer-base.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer.js
- src/layers/xr-layer/xr-layer.js
- src/microscopy-viewer.js
- webpack.component.prod.js
- webpack.config.js
- webpack.site.prod.js
These are the fixes that are purely automatic. I'm going to branch from this and get started on the ones that need to be be done by hand.
(If something in here isn't really what you want, I suggest that we merge this for now (since I'm building on top of it), but make an issue to change the rule that's not right.)
> apply prettier and eslint --fix

- package-lock.json
@ilan-gold : Can you check if your npm is up to date? I get this:
```
$ npm --version
6.11.3
```
... and can you confirm that if you run `npm install` on this branch, the changes you get are minimal? (just the few libraries that might have been updated today.)
> Blow away package-lock and rebuild

- .eslintrc.yml
- src/layers/microscopy-viewer-layer/data-utils/tiff-utils.js
- src/layers/microscopy-viewer-layer/data-utils/zarr-utils.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer-base.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer.js
Again, I'm also getting changes from prettier running in my IDE on save.
> Fix unused imports

- demo/src/App.js
The first part of this got committed to mccalluc/eslint-followup  by mistake. Fix #42, fix #22.
> Add a blurb, and change to horizontal labelled controls

- .eslintrc.yml
- CHANGELOG.md
- demo/src/App.css
- demo/src/App.js
- src/layers/microscopy-viewer-layer/data-utils/tiff-utils.js
- src/layers/microscopy-viewer-layer/data-utils/zarr-utils.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer-base.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer.js
- src/microscopy-viewer.js
- test.sh
I'm listing all the errors we get now, and Travis should be happy. Not sure how microscopy-viewer got past prettier.
> Ignore Eslint for now

- CHANGELOG.md
- README.md
- demo/src/App.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer-base.js
> Add channel toggling

- CHANGELOG.md
- rollup.config.js
> Update umd build name

- CHANGELOG.md
- src/layers/XRLayer/xr-layer-fragment.glsl
Honestly, not sure what changed - luma.gl seems to have added a dep so maybe it was that?
> Fix shaders

- CHANGELOG.md
- src/layers/StaticImageLayer.js
- src/layers/VivViewerLayer/VivViewerLayer.js
> Trigger re-render on loader prop change

- CHANGELOG.md
- demo/src/App.js
- src/layers/VivViewerLayer/VivViewerLayer.js
> Check for getRaster on loader before rendering baseLayer

- CHANGELOG.md
- demo/src/App.js
- demo/src/components/ChannelController.js
- demo/src/constants.js
- src/layers/StaticImageLayer.js
- src/loaders/OMETiffLoader.js
- tests/layers_views/layers/StaticImageLayer.spec.js
This allows `loaderSelection` updates in `StaticImageLayer`.
I also updated the fill value for hovering.
> Fix loaderSelection bug

- CHANGELOG.md
- docs/OMETIFF_LOADING.md
- src/loaders/OMETiffLoader.js
Documenting what we have here: https://github.com/hubmapconsortium/portal-containers/pull/22 and adding a little code fix for potential future use cases.
> Update docs and add offset parameter for bioformats 6

- CHANGELOG.md
- docs/IMAGE_RENDERING.md
- docs/SAMPLES.md
- src/layers/XRLayer/XRLayer.js
- src/loaders/OMETiffLoader.js
- src/loaders/index.js
- Add working links for images
- Clarify some things
- Fix tiff loader docs
> Clean up docs a bit

- CHANGELOG.md
- src/loaders/OMETiffLoader.js
This PR allows for numeric indexing on the tiff loader.
> TIFF Numeric Indexing

- CHANGELOG.md
- package-lock.json
- package.json
This seems to work and makes it cleaner to install Viv (see: https://github.com/hubmapconsortium/vitessce/issues/542 for the push behind this).
> Clean up deps

- CHANGELOG.md
- webpack.config.component.js
This seems to do the trick.  You can check out to test for yourself if you'd like.
Fixes #189.
> Don't Minify ES Bundle

- CHANGELOG.md
- docs/SAMPLES.md
- src/index.js
- Export constants relevant for developing a slider component.
- Update docs.
> Export contstants

- CHANGELOG.md
- demo/src/constants.js
Fixes #210 by moving red down to a lower position in our default selections and moving magenta up.
> Change default color

- CHANGELOG.md
- demo/src/source-info.js
- demo/src/utils.js
- package-lock.json
- package.json
I also added another RGB image to make sure everything is kosher with the new GeoTIFF.
> Move back to geotiff releases

- CHANGELOG.md
- src/index.js
- src/layers/index.js
In case you end up needing it....probably a good idea to export it anyway.
> Export XRLayer

- CHANGELOG.md
- src/constants.js
- src/layers/ScaleBarLayer.js
Related to https://github.com/hubmapconsortium/vitessce/issues/690
> Update font family

- avivator/src/source-info.js
> Update demo links

- CHANGELOG.md
- avivator/src/Avivator.js
- avivator/src/components/SnackbarAlerts.js
- avivator/src/utils.js
> Fix snackbar.

- CHANGELOG.md
- src/layers/XRLayer/xr-layer-fragment-colormap.webgl1.glsl
- src/layers/XRLayer/xr-layer-fragment-colormap.webgl2.glsl
- src/layers/XRLayer/xr-layer-fragment.webgl1.glsl
- src/layers/XRLayer/xr-layer-fragment.webgl2.glsl
Fixes an issue we saw from https://github.com/hms-dbmi/vizarr/pull/15 with sliders that have a diff less than 1.
> Fix sliders calc in shaders.

- CHANGELOG.md
- avivator/src/Avivator.js
- avivator/src/components/ChannelController.js
- avivator/src/source-info.js
As per conversation, this fixes the slider ranges and adds the new sources.
> Fix sliders and add source.

- CHANGELOG.md
- avivator/src/Avivator.js
- avivator/src/components/Dropzone.js
- avivator/src/components/Menu.js
- avivator/src/components/SnackbarAlerts.js
- avivator/src/index.js
- avivator/src/source-info.js
- avivator/src/utils.js
- docs/OMETIFF_LOADING.md
- package-lock.json
- package.json
- src/loaders/fileStore.js
- src/loaders/index.js
- tutorial/README.md
@manzt Can you check this out and give it a whirl?  If it works for you, I'll deploy a demo for Nils to try.
> Support local tiff files.

- tutorial/README.md
Sorry, meant to add this to the LZW PR but it slipped my mind.
> Update Tutorial README.md

- CHANGELOG.md
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/MultiscaleImageLayer/utils.js
> Add onClick callback for Layers

- CHANGELOG.md
- avivator/src/Avivator.js
- avivator/src/components/SnackbarAlerts.js
- avivator/src/utils.js
I noticed some funny business in the snackbars, so this should clean things up a bit.
1. The default error was not displaying properly
2. We always showed the "this is a random image" snackbar regardless of the image.
> Fix snackbars.

- CHANGELOG.md
- package.json
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/OverviewLayer.js
Was so excited I forgot to remove our own usage of scale/translate!
> Remove Internal Usage of Scale

- CHANGELOG.md
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/XRLayer/XRLayer.js
I don't think we ever made an issue for this, but this should fix the issue we were having with padding tiles.  Do we have something we can test this on?  Maybe in vizarr on one of the images that made you discover this fix?
> Fix tile padding issues.

- CHANGELOG.md
- avivator/README.md
Feel free to close this or edit if it does not make sense.
> Avivator README

- CHANGELOG.md
- avivator/src/Avivator.js
- avivator/src/index.js
> Don't Display Snackbar When Demo Image URL Is Provided

- CHANGELOG.md
- README.md
This fixes a broken link to bioformats in the docs site
> Fix readme link

- .github/workflows/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
Now that we have a growing number of contributors, we should create some templates I think.  Open to suggestions, just pulled this right from Vitessce.
> Add Github Issue Templates

- CHANGELOG.md
- documentation.yml
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/views/utils.js
Responding to: https://github.com/hms-dbmi/viv/issues/307#issuecomment-745008741 and https://github.com/hms-dbmi/viv/issues/307#issuecomment-745696381 this function improves the `getDefaultInitialViewState` utility and documents it more clearly.
> Update getDefaultInitialViewState function

- CHANGELOG.md
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
> Tile Indexing Should Be Offset When Transformation Scales

- CHANGELOG.md
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
> Fix maxZoom Calculation for Small Tile Sizes

- README.md
Should this look like the "Related Software" section with short descriptions or is this OK?
> 3rd party tools Added to README

- CHANGELOG.md
- src/layers/ImageLayer.js
> Fix `ImageLayer` `loader` type.

- CHANGELOG.md
- src/constants.ts
- src/index.js
- src/layers/VolumeLayer/VolumeLayer.js
- src/layers/VolumeLayer/XR3DLayer/XR3DLayer.js
- src/layers/VolumeLayer/XR3DLayer/channel-intensity-module.js
- src/layers/VolumeLayer/XR3DLayer/channel-intensity.glsl
- src/layers/VolumeLayer/XR3DLayer/index.js
- src/layers/VolumeLayer/XR3DLayer/rendering-modes.js
- src/layers/VolumeLayer/XR3DLayer/xr-layer-fragment.glsl
- src/layers/VolumeLayer/XR3DLayer/xr-layer-vertex.glsl
- src/layers/VolumeLayer/index.js
- src/layers/VolumeLayer/utils.js
- src/layers/index.js
- src/layers/utils.js
- src/loaders/tiff/lib/utils.ts
- src/viewers/VivViewer.js
- src/viewers/VolumeViewer.js
- src/viewers/index.js
- src/views/VolumeView.js
- src/views/index.js
- tests/layers_views/layers/VolumeLayer.spec.js
- tests/layers_views/layers/index.js
First PR for #398.  The next PR's will be for updating Avivator.
It is common to produce datasets with a 3rd spatial dimension that can be visualized as a volume.  This PR allows Viv's core to render these datasets as volumes.
- We allow for arbitrary affine transformations as well as physical-size based scaling.   This scaling is common for light sheet experiments where fewer z-planes are captured than the ratio of the height/width/depth of the physical sample suggests.  Therefore in order to render correctly, we need to "scale" the dimensions of the volume and this happens automatically if physical size scaling is found on the loader.
- There are 3 rendering modes - Max Intensity Projection, Min Intensity Projection, and Additive, for both "colormapping" and "blended" modes.
- All three …
> 3D Viv Core

- src/layers/VolumeLayer/VolumeLayer.js
Small change requested by Nils.
> Add progress indicator option + onUpdate callback + Fix Font

- CHANGELOG.md
- src/viewers/VolumeViewer.js
Small error noticed in the docs
> Fix VolumeViewer props docs.

- CHANGELOG.md
- avivator/src/hooks.js
I find myself logging this information out a lot and/or checking this for people, so figured I'd add a logging statement.
> Log Metadata for Avivator.

- CHANGELOG.md
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VivViewer.js
Fixes #461 
- Pass `glOptions` from the viewers to `DeckGL`
> Pass glOptions from the viewers to DeckGL

- CHANGELOG.md
- README.md
> Update README with Node Version

- CHANGELOG.md
- src/viewers/VivViewer.jsx
Fixes #511
- Fix picking on `VivViewer`
> Fix picking for `VivViewer`

- CHANGELOG.md
- docs/SAMPLES.md
Did not work out of the box but should now.
> Fix `SAMPLES.md`

- .eslintrc.yml
- CHANGELOG.md
- avivator/src/Avivator.jsx
- avivator/src/components/Controller/Controller.jsx
- avivator/src/components/Controller/components/AddChannel.jsx
- avivator/src/components/Controller/components/CameraOptions.jsx
- avivator/src/components/Controller/components/ChannelController.jsx
- avivator/src/components/Controller/components/ColormapSelect.jsx
- avivator/src/components/Controller/components/GlobalSelectionSlider.jsx
- avivator/src/components/Controller/components/LensSelect.jsx
- avivator/src/components/Controller/components/Menu.jsx
- avivator/src/components/Controller/components/MenuTitle.jsx
- avivator/src/components/Controller/components/PanLockToggle.jsx
- avivator/src/components/Controller/components/PictureInPictureToggle.jsx
- avivator/src/components/Controller/components/RenderingModeSelect.jsx
- avivator/src/components/Controller/components/SideBySideToggle.jsx
- avivator/src/components/Controller/components/Slicer.jsx
- avivator/src/components/Controller/components/VolumeButton.jsx
- avivator/src/components/Controller/components/ZoomLockToggle.jsx
- avivator/src/components/Footer.jsx
- avivator/src/components/Snackbars/Snackbars.jsx
- avivator/src/components/Viewer.jsx
- avivator/src/hooks.js
- avivator/src/state.js
Following up on https://github.com/hms-dbmi/viv/pull/529#discussion_r761947109
- Refactor Zustand to use Best Practioce
> Refactor Zustand for Best Practice

- .github/workflows/build_and_deploy.yml
- CHANGELOG.md
ugh, hard to debug deploy issues..
> feat: deploy avivator via gh-pages (#548)

- .github/workflows/build_and_deploy.yml
- CHANGELOG.md
> fix: github workflow deployment steps

- CHANGELOG.md
- tutorial/README.md
Formalizes https://github.com/hms-dbmi/viv/discussions/546.  I'm open to putting this in other places as well, but this seemed like a good spot.
- Add note about port forwarding to tutorial
> Port Forwarding Note

- CHANGELOG.md
- avivator/src/hooks.js
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/utils.js
Viv fix for https://github.com/vitessce/vitessce/issues/1172
- Don't allow `extensions` to propagate to the custom `BitmapLayer` to prevent redefinition of variables
> Fix interleaved RGB shader compilation

- CHANGELOG.md
- avivator/src/utils.js
Temporary workaround for Avivator.
> fix(avivator): temporarily disable worker pool usage

- .meta-updater/main.mjs
- CHANGELOG.md
- package.json
- packages/constants/package.json
- packages/extensions/package.json
- packages/layers/package.json
- packages/loaders/package.json
- packages/main/package.json
- packages/types/package.json
- packages/viewers/package.json
- packages/views/package.json
- sites/avivator/package.json
- sites/docs/package.json
> v0.13.0-alpha.0

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
Noticed during release - if this is not already installed globally, you cannot do a release.
- Add package to our dev dependencies.
> (chore): Add `@pnpm/meta-updater` to project.

- CHANGELOG.md
- README.md
> chore: fix readme typos

- CHANGELOG.md
- sites/avivator/src/components/Controller/components/ChannelController.jsx
- sites/avivator/src/components/Controller/components/ChannelOptions.jsx
Fixes #582 
- Move channel removal to its own button from channel options dropdown
- Add max/min options in channel options dropdown
> Add Max/Min + Full Toggling for Channels Sliders

- .github/workflows/gh-pages.yml
- .github/workflows/test_and_publish.yml
- README.md
- packages/main/README.md
- sites/docs/src/3D_RENDERING_BRIEF.md
- sites/docs/src/CUSTOM_SHADERS.md
- sites/docs/src/IMAGE_RENDERING.md
> Update references to master branch to main

- CHANGELOG.md
- sites/avivator/src/constants.js
- sites/avivator/src/hooks.js
- sites/avivator/src/utils.js
> fix(avivator/ome-zarr): handle missiing selectable dimension

- .changeset/large-dragons-exist.md
- packages/loaders/src/zarr/index.ts
> fix(loaders): Throw error for missing METADATA.ome.xml

- .changeset/tall-insects-act.md
- packages/loaders/src/omexml.ts
> fix(loaders): Allow `unknown` OME-XML Description

- sites/avivator/src/utils.js
Fixes #
* 3D Channel Stats
- Changed the function: getSingleSelectionStats3D in Utils.JS
> Bugfix 3D Channel Stats

- .changeset/chatty-ravens-collect.md
I missed the changeset in the PR for upgrading deck.gl/luma.gl
-
> (chore): add changeset for version upgrade

- README.md
> chore: Fix typo in README to tutorial
