hms-dbmi/viv

- demo/src/App.js
- package-lock.json
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer.js
- src/layers/xr-layer/xr-layer-fragment.js
- Added a lower bound for slider values
- Learned that vector-arrays need to be flattened to be passed onto the shaders (discovering https://github.com/hubmapconsortium/vitessce-image-viewer/issues/28 in the process when I also tried to convert the color values into an array instead of separate uniforms as they [are now](https://github.com/hubmapconsortium/vitessce-image-viewer/compare/ilan-gold/min-range-sliders?expand=1#diff-f0ec75b05ef1b19b4cd7be905e1943b7R74))
> Add lower bound for sliderValues

- README.md
- demo/src/App.js
- demo/src/source-info.js
- package-lock.json
- package.json
- src/layers/microscopy-viewer-layer/data-utils/index.js
- src/layers/microscopy-viewer-layer/data-utils/tiff-utils.js
- src/layers/microscopy-viewer-layer/data-utils/zarr-utils.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer-base.js
- src/layers/microscopy-viewer-layer/microscopy-viewer-layer.js
- webpack.config.js
This looks to finish the work for #15  and #30.  Once this is merged (or rather while it's under review), I will begin working on integrating pyramidal tiff into vitessce and vitessce-data.  Since the tiff pyramid is a fairly "standard" format in my eyes, I will thus look to make this the default in vitessce and hold off on zarr.
> Integrate TIFF access into vitessce-image-viewer and Improve Metadata Caching

- CHANGELOG.md
- src/layers/xr-layer/xr-layer-vertex.js
- `gl_Position` is the on-screen coordinates (the viewport scaled down to `[-1,1]`)
- `vTexCoord` is one of `[[0,0],[0,1],[1,0],[1,1]]` corresponding to a coordinate system for the fragment shader to use post-rasterization (i.e rasterization chops up this unit-square into "fragments" and each fragment is processed by the fragment shader)
> Clean up vertex shader

- CHANGELOG.md
- src/layers/xr-layer/xr-layer-fragment.js
- The ramp function is global to the shader, not to our own conversion (i.e if you tried passing in RGB values outside of the [0,1] bound or tried requesting such data from the sampler, the ramp function would kick in).  So a negative value in hsv, which is what happens when the channel is turned off, subtracts from the brightness.   Fixes #85
> Fix Brightness

- CHANGELOG.md
- package.json
- src/loaders/zarrLoader.js
Re: #108. Tests seem to be faster now -- thanks! This PR adds `test:watch` which allows for on-save re-running of tests during development. I also cleaned up a couple lines in the loader that we had discussed in #113.
> add test:watch and clean up zarr loader

- CHANGELOG.md
- demo/src/initLoaders.js
- package-lock.json
- package.json
- src/index.js
- src/layers/StaticImageLayer.js
- src/loaders/index.js
- src/loaders/zarrLoader.js
The `level` prop was hardcoded within Viv for `getRaster`. This PR moves setting the selection to the loader instead.
> Move raster selection to loader

- CHANGELOG.md
- demo/src/initLoaders.js
- src/layers/XRLayer/XRLayer.js
- src/loaders/index.js
- src/loaders/tiffPyramidLoader.js
Some arguments for the zarr/tiff loaders are not necessary and are requiring more hardcoded logic in vitessce.
> Simplify image loaders

- CHANGELOG.md
- demo/src/App.js
- src/layers/StaticImageLayer.js
- src/layers/VivViewerLayer/utils.js
- src/layers/XRLayer/XRLayer.js
- src/layers/XRLayer/xr-layer-fragment-colormap.glsl
- Fixes  #127
- Generalizes to allow for multi-channnel, single colormap
The second point I would like some input on.  When I first did this, I figured only one channel at a time would be fine but making that [small change](https://github.com/hubmapconsortium/vitessce-image-viewer/compare/master...ilan-gold/fix_colormap#diff-7521b7078eea189519ea0dc27ea4fae1R71) to fix the fact that `draw` was not being called broke a lot of stuff so I figured I'd give this an overhaul.  Do we want to support multiple colormaps at once?  If so, I could do that, probably.
> Fix and Generalize Colormap

- CHANGELOG.md
- README.md
- src/layers/StaticImageLayer.js
- src/layers/VivViewerLayer/VivViewerLayer.js
- src/loaders/zarrLoader.js
This fixes #68 addressing two problems at once:
- There is currently an issue where zooming out too far leaves the viewer without an image
- Zooming and panning previously could cause the user to see black splotches of unloaded regions, but no longer.
> Add Background image

- CHANGELOG.md
- src/layers/StaticImageLayer.js
- src/layers/VivViewerLayer/VivViewerLayer.js
- src/layers/VivViewerLayer/VivViewerLayerBase.js
- src/layers/VivViewerLayer/utils.js
- src/layers/XRLayer/XRLayer.js
- src/loaders/tiffPyramidLoader.js
- src/loaders/utils.js
- src/loaders/zarrLoader.js
- tests/StaticImageLayer.spec.js
- tests/utils.spec.js
- tests/zarrLoader.spec.js
I removed `loader.vivMetaData` from the loaders and now require the loaders to have the properties:
- `dtype`
- `tileSize` 
- `numLevels` - number of pyramidal levels
Also, for `StaticImageLayer` the loader must implement `loader.getRasterSize({z})` which returns `({imageWidth, imageHeight})` for a particular zoom level. 
Overall, I noticed that we were doing somethings within `viv` that were still more aware of the data source than I thought made sense. Let me explain.
For example, the reason that we needed `isTileInBounds` was to prevent making wrapping requests for x/y tile requests which is `geotiff`-specific and to avoid making requests for negative `bbox` values from deck.gl in `renderSubLayers`. Allowing wrapping behavoir makes sense in the geospatial case and the `geotiff` …
> minZoom refactor & force loaders to implement `onTileError`

- CHANGELOG.md
- src/layers/StaticImageLayer.js
Refactoring the `getRaster` function to return an image (`{data, width, height}`) and using `StaticImageLayer` to manage data changes made it so that loader change events were not registered in the `XRLayer` (i.e. changing a channel selection does not trigger new render),
This PR simply wraps the image data (managed by `StaticImageLayer`) in a Promise so that `XRLayer` checks for a new promise and can resolve and render.
> Aysnc data in `StaticImageLayer`

- CHANGELOG.md
- README.md
- demo/src/App.css
- src/VivViewer.js
Fixes #116, but different than asked.  As per [React docs](https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes), hooks do not currently support catching children errors, so I think the component displaying an error is good.  Do you think we should go differently?  I suppose we could throw an error, and then tell people to wrap the component in a class based component to catch the error.  I think this solution allows for people to style the error with css, but I could have that wrong.
> Check for safari

- CHANGELOG.md
- demo/src/App.js
- demo/src/utils.js
- docs/SAMPLES.md
- src/loaders/OMETiffLoader.js
- src/loaders/utils.js
- src/loaders/zarrLoader.js
- tests/loaders/OMETiffLoader.spec.js
- tests/loaders/zarrLoader.spec.js
Removes `loader.serializeSelection` in favor of standardizing what `loaderSelection` is for the `loader.getTile` and `loader.getRaster` callbacks.
> Remove `loader.serializeSelection`

- CHANGELOG.md
- demo/src/App.js
- demo/src/components/ChannelController.js
- demo/src/constants.js
- src/layers/OverviewLayer.js
- src/layers/ScaleBarLayer.js
- src/layers/StaticImageLayer.js
- src/layers/VivViewerLayer/VivViewerLayer.js
- src/layers/VivViewerLayer/VivViewerLayerBase.js
- src/layers/VivViewerLayer/utils.js
- src/layers/XRLayer/XRLayer.js
- src/layers/XRLayer/xr-layer-fragment.glsl
- src/layers/XRLayer/xr-layer-vertex.glsl
- src/viewers/PictureInPictureViewer.js
- src/viewers/VivViewer.js
This fixes #154 by enabling [picking](https://github.com/visgl/deck.gl/blob/43593122c23a64b1afbe0593d028ab6b649a9a93/docs/developer-guide/custom-layers/picking.md) on our layers (updating shaders as well as props) and then implementing the right things in our other classes/components.
I am aware that the hover stops working when you zoom out on the tiled layer - I opened up a PR into deck.gl to resolve this here: https://github.com/visgl/deck.gl/pull/4526
> Add getting the point on hover

- CHANGELOG.md
- src/loaders/OMETiffLoader.js
I am adding a dimension builder here for the OMETIFF loader.  When I start doing the CODEX integration with Vitessce, Vitessce will need a way of inferring dimensions rather than pulling them from an external schema like `xxx.rasters.json`.  Does this make sense?  Even if this isn't the final product, it can serve as a starting point that I can iterate on with CODEX.
> Add a dimension builder onto the tiff loader.

- CHANGELOG.md
- demo/src/source-info.js
- docs/OMETIFF_LOADING.md
- documentation.yml
- src/loaders/OMETiffLoader.js
- src/loaders/index.js
This will allows us to start accessing data without the new url scheme so we can demo CODEX data.  Related to: https://github.com/hubmapconsortium/portal-ui/issues/189.
> Tiff Request Headers

- CHANGELOG.md
- demo/src/source-info.js
- src/layers/VivViewerLayer/VivViewerLayer.js
- src/layers/VivViewerLayer/VivViewerLayerBase.js
- src/layers/VivViewerLayer/utils.js
- src/layers/XRLayer/XRLayer.js
- src/loaders/OMETiffLoader.js
- src/loaders/utils.js
This removes the code for handling unpadded tiles.  In general, though, we should be robust to this via #192 but for now this is a good step forward.  I'll merge once I update the docs to reflect that we should use the new `portal-containers` version for pyramid-generation but in the meantime would love the review/a checkout of the branch to make sure I didn't miss something.  Thanks!
> Remove Bioformats Hack

- CHANGELOG.md
- src/layers/OverviewLayer.js
- src/loaders/OMETiffLoader.js
- src/views/OverviewView.js
- tests/layers_views/views/OverviewView.spec.js
This fixes #198 and also resolves the weirdness that was happening in the overview for the zarr COVID-19 image since it is longer than it is wide.  I assumed that it was a result of a #198 but they turned out to be unrelated, so we now handle height > width differently than width > height in the OverviewView when calculating dimensions.
**Before**:
**After**:
> Update sizing in overview

- CHANGELOG.md
- src/constants.js
- src/layers/XRLayer/XRLayer.js
Our current feature detection inspects the `document` object when importing viv, checking to see if WebGL2 is available. This is an issue for two reasons:
1.) If viv is loaded as a module outside of the browser (i.e. in a static build tool like Next.js/Gatsby that creates an bundled app with tree-shaking), the `document` doesn't exist and will throw an error. In addition, having feature detection as a global constant is in general a foot-gun. I ran into this issue because I was using viv with Next.js, and fortunately it failed loudly because the document doesn't exist. However, if we were able to feature detect in the server environment, then whatever the server detects would get sent to all clients (regardless of the browser they are using).
2.) We are checking whether WebGL2 is …
> Use current GL context to determine shaders/textures

- CHANGELOG.md
- src/constants.js
- src/loaders/OMETiffLoader.js
See https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Pixels_Type for the error (`float` not `float32`).  This is an issue with the MALDI IMS in the portal.
> Fix 32 bit float error for OMEXML

- CHANGELOG.md
- src/layers/VivViewerLayer/VivViewerLayerBase.js
- src/loaders/OMETiffLoader.js
I think this is a little more robust, since it accounts for both directions and we have this new nice padding function.  We have some data that `bioformats2raw` mistiled (I think) in the height direction so this should help that a bit.
> Pad tiles Better

- CHANGELOG.md
- src/layers/OverviewLayer.js
- src/layers/StaticImageLayer.js
- src/layers/VivViewerLayer/VivViewerLayer.js
- src/layers/utils.js
There has been a resurgence of #195 that I assume is related to an issue with `bioformats2raw` that we were seeing with tile boundaries (addressed in #223).
This guarantees that the background image and the overview image are a power of 2 so that it always binds to the texture (shouldn't be necessary, and I am going to actually report this to luma.gl soon but for now this will gives us an ironclad guarantee).  This is necessary for the CCF-UI which uses picture-in-picture extensively.
cc @bherr2
> Fix PictureInPictureViewer when Low Res Tile Doesn't Bind

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
This provides a temporary fix for #236.  We need to bump our `node` environment because the `TextDecoder` API apparently does not exist on 10 (12 is the same as geotiff and 13 doesn't have some gl package).
> Geotiff String Data Issue

- CHANGELOG.md
- avivator/src/Avivator.js
- avivator/src/components/Dropzone.js
- avivator/src/components/Menu.js
- avivator/src/components/SnackbarAlerts.js
- avivator/src/utils.js
- src/loaders/fileStore.js
- src/loaders/index.js
- tutorial/README.md
Adds a zarr`FileStore` class which is simply a mapping of zarr keys to `File` objects. My current understanding wrt directories is that without the [Native File System API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem), you can't randomly request to read files from a directory by path name. 
That means you can't create `File` objects on-demand, and instead we need get all the files up front and create an index that maps zarr keys to blobs. With that said, the current example works well! I'd just worry if someone had a massive pyramid.
> Add support for local bfmts zarr

- CHANGELOG.md
- webpack.config.component.js
The UMD is in theory supposed to be used in a `script` tag so bundling it with its dependencies makes more sense than not (except React, which should never be bundled except for a web page AFAIK).
> Bundle UMD with Dependencies (Except React)

- CHANGELOG.md
- src/index.js
Exports the custom `HTTPStore` with abort signal support.
> Export HTTPStore

- CHANGELOG.md
- package-lock.json
- package.json
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
This fixes #217 by upgrading to a version of deck.gl that supports `modelMatrix` as a prop for `TileLayer`.  We should be able to handle arbitrary affine transformations (the screenshots are of rotation + translation and a shear operation) now in the `MultiscaleImageLayer` via this prop.
I also removed the `scale`  and `translate` props from `ImageLayer` so that everything is uniform across our layers using `modelMatrix`.
When implementing this for https://github.com/hms-dbmi/vizarr/pull/43 with @will-moore I gave [some notes here](https://github.com/hms-dbmi/viv/issues/217#issuecomment-719856944) to avoid the headaches I encountered about creating the transformation matrices.  Xiaoji also brought up a good point [about memory usage](https://github.com/visgl/deck.gl/issues/5047#issuecommen …
> Upgrade to deck.gl 8.4.0-alpha.2

- .prettierrc.json
- CHANGELOG.md
- src/viewers/PictureInPictureViewer.js
- src/views/DetailView.js
- src/views/OverviewView.js
- src/views/index.js
- tests/layers_views/views/DetailView.spec.js
- tests/layers_views/views/OverviewView.spec.js
This addresses #330. I don't have an easy way to test this but a very similar implementation with subclasses worked in my app. I only tried it with one image but there the combination of `zoom` and `scale` properly transformed the coordinates such that the mouse was in the center of the red bounding rectangle after a click.
> Add click handler to OverviewView that centers the detail view

- CHANGELOG.md
- package.json
- src/index.js
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VivViewer.js
This addresses #329. The callback may change the view state, just like the [deck.gl callback](https://deck.gl/docs/api-reference/core/deck#onviewstatechange).
Add "onViewStateChange" to VivViewer, PictureInPictureViewer, SideBySideViewer.
Fix JSDoc `@param` and indicate optional parameters.
Export OverviewLayer.
> onViewStateChange callback for viewers

- CHANGELOG.md
- src/layers/BitmapLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
This came up with @nhpatterson but because deck.gl does all their operations before the hook, we need to explicitly pass in a `transparentColor` in the native color space of the data.  `[16, 128, 128]` is black (`[0, 0, 0, 0]`) in that space.  In other words, they apply opacity in the YCbCr space and then we apply the transformation to the RGB space, so the `transparentColor` which is usually `[0,0,0,0]` needs to be converted ahead of time into YCbCr space.
Here is the relevant code in deck.gl:
https://github.com/visgl/deck.gl/blob/09a4bbf2041f77af18f3d54904c366f22e501f9e/modules/layers/src/bitmap-layer/bitmap-layer-fragment.js#L80-L83
To test this out without loading it into Vitessce, you can change the `opacity` prop here:
https://github.com/hms-dbmi/viv/blob/a177a0eecd4041306b3b7bf9c3ae …
> Fix Opacity Calculation for YCbCr Images

- CHANGELOG.md
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
#339 revealed a bug in our `minZoom` calculation.  It should be transformed [just like `maxZoom`](https://github.com/hms-dbmi/viv/blob/master/src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js#L132) and our [tile fetching zoom level](https://github.com/hms-dbmi/viv/blob/master/src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js#L104) to account for deck.gl's zoom level calculation [by tile size](https://github.com/hms-dbmi/viv/blob/9b02611363c0cc20732190e77a4cec12ef0502db/src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js#L98-L103).  Also, I think the visibility condition can be simplified further - no reason not to just show the image always when opacity is 1.  This makes things clearer.
> Fix minZoom Bug and Simplify Opacity Conidition

- CHANGELOG.md
- src/layers/BitmapLayer.js
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayerBase.js
- src/layers/XRLayer/XRLayer.js
- src/layers/XRLayer/shader-modules/channel-intensity.glsl
- src/layers/XRLayer/xr-layer-fragment-colormap.webgl1.glsl
- src/layers/XRLayer/xr-layer-fragment-colormap.webgl2.glsl
- src/layers/XRLayer/xr-layer-fragment.webgl1.glsl
- src/layers/XRLayer/xr-layer-fragment.webgl2.glsl
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
Fixes #343.
To test this out you can use [the Vanderbilt Kidney image](http://localhost:8080/?image_url=https://viv-demo.storage.googleapis.com/Vanderbilt-Spraggins-Kidney-MxIF.ome.tif) and then set the [default prop](https://github.com/hms-dbmi/viv/blob/ilan-gold/transparent_color/src/viewers/PictureInPictureViewer.js#L64) to `true` and the [background color to white](https://github.com/hms-dbmi/viv/blob/ilan-gold/transparent_color/avivator/src/index.css#L8) in Avivator or use the colormaps with the normal black background. 
The use case is mainly for IMS images from the portal [like this one](http://localhost:8080/?image_url=https://assets.hubmapconsortium.org/be503a021ed910c0918842e318e6efa2/ometiff-pyramids/ometiffs/VAN0006-LK-2-85-IMS_PosMode_multilayer.ome.tif?token=) which you can …
> Transparent Color Prop

- CHANGELOG.md
- README.md
- tutorial/README.md
It was recently brought to my attention that we support implementations of the new [TIFF pyramid spec](https://ome.github.io/design/OME005/) of which `bioformats2raw + raw2ometiff` is only one.  `bfconvert` is another and I have added information about this.  @nhpatterson created an implementation (maybe unintentionally?) in Python and his images work in Viv as well now.
> Add note about `bfconvert` and New TIFF Pyramid Spec

- CHANGELOG.md
- src/constants.js
- src/index.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/index.js
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/global-selection-hook.js
- src/views/DetailView.js
- src/views/SideBySideView.js
- src/views/utils.js
This implements the smooth global selection transitions discussed in #351. It maintains the last successfully loaded selection in `PictureInPictureViewer`. If the newly selected selection differs from the last loaded one, `DetailView` creates two instances of `MultiscaleImageLayer`, each with a different loader selection. The top layer for the new loader selection has a callback `onViewportLoad` that will make the new selection the successfully loaded one.
Because `GLOBAL_SLIDER_DIMENSION_FIELDS` is needed, it is duplicated from the Avivator constants. It is recommended that Avivator would get this constant from Viv in the future instead of maintaining its own copy.
This also exports `BitmapLayer`, the original request in #351.
> Smooth Global Selection Transitions

- .github/workflows/test.yml
- CHANGELOG.md
This allows PR events to trigger our tests/builds on GH actions.  I think this is the way to go for handling forked repos so that our tests run against them but maybe I have this wrong?
See: https://github.com/visgl/deck.gl/blob/6136d93d19ef098685f3e9b5ecd74ea5a8d701fa/.github/workflows/test.yml#L4-L8
> Allow for PR GH Actions.

- CHANGELOG.md
- package-lock.json
- package.json
Addresses https://github.com/geotiffjs/geotiff.js/issues/193 on our end.  Here is the diff with our current branch: https://github.com/ilan-gold/geotiff.js/compare/ilan-gold/viv_release_080...ilan-gold:ilan-gold/viv_083?expand=1#
Basically, it is possible for tiff fetch sources to request data outside the size of the file which results in a 416 error from the server.  This PR upgrades our geotiff version to one that makes sure that no requests are made for data outside that range.
You can test this out using http://localhost:8080/?image_url=https://vitessce-demo-data.storage.googleapis.com/test-data/VAN0006-LK-2-85-IMS_PosMode_multilayer.ome.tif?token= (and on Avivator to see the difference) and then selecting the last channel - in Avivator, it will not work but here it will.
> Fix out of range fetch isssue for Tiff

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VivViewer.js
- src/views/OverviewView.js
- src/views/SideBySideView.js
- src/views/VivView.js
- tests/layers_views/views/OverviewView.spec.js
- tests/layers_views/views/VivView.spec.js
This addresses #353. Contrary to what I wrote before, @ilan-gold's implementation already worked for `SideBySideViewer`. One only had to set `viewStates` instead of `viewState` in Avivator. I tested it extensively with different view states for the left and right views.
I implemented the state update that I proposed in #353. I made some tweaks to the comparisons to make it possible to add view state for a view that didn't initially have that prop. I replaced `lodash.isequal` with `fast-deep-equal` because it is seven times as fast in a benchmark reported in their repo. Also, you already had it as an indirect dev dependency.
I updated all failing tests to the new props.
> Set View State from Props

- CHANGELOG.md
- package-lock.json
- package.json
- src/loaders/zarr/index.ts
- src/loaders/zarr/lib/storage.ts
- src/loaders/zarr/lib/utils.ts
- src/loaders/zarr/pixel-source.ts
Upgrades zarr.js to v0.4. 
- Removes our custom `HTTPStore` since `zarr.HTTPStore` supports passing `RequestInit` (including signal) in `getRawChunk`. 
- Replaces our hierarchy traversal (concatonating url paths + `getJson` for metdata) with zarr's built-in hierarchy traversal (`openGroup`, `grp.getItem(arrayPath)`).
- Uses `Attributes` object to read `.zattrs`. 
- _Finally_ removes those annoying 404s for `.zgroup` when trying to open an array.
> Upgrade zarr@0.4

- CHANGELOG.md
- src/loaders/index.ts
I accidentally exported `*` and not `default` for each PixelSource. This corrects the exports.
> Export default not * from pixel-sources

- CHANGELOG.md
- src/loaders/zarr/lib/indexer.ts
Indexing a `ZarrPixelSource` with an `number[]` selection would mutate the original selection (not good!). This PR changes the zarr indexer to create a copy of the selection that is safe to mutate.
> Don't mutate Zarr chunk selection

- CHANGELOG.md
- src/views/DetailView.js
- src/views/SideBySideView.js
- tests/layers_views/views/DetailView.spec.js
- tests/layers_views/views/SideBySideView.spec.js
Fixes #376
- `physicalSizes` moved to the `meta` attribute and off of the loader itself - we did not update the `DetailView` or `SideBySideView` to reflect this.
- `value` -> `size` in the loaders so this needs to be used as such in the views as well
> Fix Scale Bar in Views

- CHANGELOG.md
- src/loaders/zarr/bioformats-zarr.ts
- src/loaders/zarr/lib/utils.ts
- src/loaders/zarr/ome-zarr.ts
- src/loaders/zarr/pixel-source.ts
- tests/loaders/bioformats-zarr.spec.js
Fixes #381
Fixes #382
Rather than inferring `tileSize` from the underlying array chunks, a _desired_ `tileSize` is now specified fro the `ZarrPixelSource`, similar to the `TiffPixelSource`. This allows us to use the _entire_ image pyramid, even when chunks are shaped differently. This change means that we can (hopefully) ensure that deck.gl gets consistently size tiles for a zarr-based pyramid.
> Remove pyramid trimming for ZarrPixelSource

- CHANGELOG.md
- src/constants.ts
- src/loaders/tiff/lib/utils.ts
- src/loaders/tiff/pixel-source.ts
- src/loaders/zarr/pixel-source.ts
This PR adds support for double-precision floating point data.
Right now we don't support double-precision floating point data but we could by casting to a Float32.  We have IMC data coming in from HuBMAP that is in this format so that is the motivation for doing this.  I think this solution requires the least amount of code while also preserving "double/Float64" as the datatype whenever someone were to `console.log` it.
- support `double` type from OME as `Float64` in Viv
- Add `Float64` support in Viv by casting to `Float32` and using the shader settings for 32 bit floats.
- Remove extraneous cast to `Float32Array` for tiff (it was a fix for a misidentified bug which was not a bug)
> Float64 Support

- CHANGELOG.md
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VivViewer.js
Fixes #389
This exposes the deck.gl `onHover` callback to the viewers, enabling tooltips.
- `onHover` prop for `VivViewer`, `PictureInPictureViewer`, `SideBySideViewer` for deck.gl callback.
I added an `onHover` callback with `console.log` to Avivator. The callback was called as expected.
> Add onHover prop

- CHANGELOG.md
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VivViewer.js
I think this is a natural extension of the `hoverHooks` API.  I have the `handleValue` hoverHook because the calculation to get the value is non-trivial and tied to knowing how the deck.gl `TileLayer` works with different tile sizes.  This extends that to just return the coordinate.  I think the `onHover` addition still has value so I'd like both to coexist.  To be merged post #390.
> Add `handleCoordinate` Hover Hook

- CHANGELOG.md
- docs/SAMPLES.md
The current documentation for `getChannelStats` just states that it takes in a TypedArray but I'm not sure people will really know what to do that immediately.  We could add a snippet like this to the documentation for the method instead of doing this, but I figured this is a good place for it since the snippet is a couple of lines and anyone who uses our components will also probably (want to) use this.  I found myself re-writing this line of code frequently in Vitessce when upgrading so it seemed like a good thing to document here.
- Add a `getChannelStats` part to the snippet.
> getChannelStats snippet

- CHANGELOG.md
- package-lock.json
- package.json
Upgrade out version of `geotiff.js` to address https://github.com/geotiffjs/geotiff.js/issues/214.
Accepted PR:
https://github.com/geotiffjs/geotiff.js/pull/215
I am working on our bringing the functionality we have in our branch right now into geotiff.js so that we can stop doing this.
> Fix SubIFDs issue

- CHANGELOG.md
- src/layers/BitmapLayer.js
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/OverviewLayer.js
- src/layers/ScaleBarLayer.js
- src/layers/XRLayer/XRLayer.js
- src/loaders/zarr/index.ts
- src/types.ts
_TL;DR: Our choice of JSDoc syntax for types is good for our documentation generator, but the actual generated TS types suffer as a result. This PR gives us the best of both worlds: the same documentation and better TS types._
We currently use JSDoc syntax to define the properties for our layers. This is good for our documentation, because `documentationJS` understands JSDoc syntax and not TS, but the choice to use JSDoc syntax means that our emitted TypeScript declarations aren't very precise or helpful. 
Essentially, current annotations denote optional/required fields and "rough" shapes, but that's about it. For example, the following is currently valid:
```javascript
import {ImageLayer} from "@hms-dbmi/viv";
const layer = new ImageLayer({
loader: {}, // just an empty object, _should_ …
```
> Improve emitted TS types for layers

- CHANGELOG.md
- avivator/src/Avivator.js
- src/views/utils.js
If you remove all channels in `Avivator`, the app crashes because the `VivView` classes in SBS and PIP don't check for empty lists.
- Check if `loaderSelection` has a first entry to prevent crashes due to it being an empty list but still truthy.
> Fix Empty Loader Selection Bug

- CHANGELOG.md
- src/loaders/utils.ts
- tests/loaders/utils.spec.js
If you passed in an array of all zeros previously, the `autoSliders` value would be undefined because we filter the array to non-zero values.  
Additionally, using 1 is too high for `Float32` data so the slider settings were often too low.  Now the [Luca7 32 bit](http://avivator.gehlenborglab.org/?image_url=https://viv-demo.storage.googleapis.com/LuCa-7color_3x3component_data.ome.tif) example works much better.
- Always return numeric value for `autoSliders` from `getChannelStats`
- Fix data filtering for `Float32` values.
> Fix Bugs in `getChannelStats`.

- CHANGELOG.md
- src/viewers/VivViewer.js
Fixes #425
- Check every property of the `info` parameter in `onHover` before accessing sub-properties.
> Check all properties in onHover to avoid crashes

- src/layers/ImageLayer.js
- src/layers/VolumeLayer/VolumeLayer.js
- src/layers/VolumeLayer/utils.js
- src/layers/XR3DLayer/XR3DLayer.js
- src/layers/XR3DLayer/xr-layer-fragment.glsl
- src/layers/XR3DLayer/xr-layer-vertex.glsl
- src/loaders/omexml.ts
- src/loaders/tiff/lib/utils.ts
- src/loaders/tiff/pixel-source.ts
- src/types.ts
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VivViewer.js
- src/viewers/VolumeViewer.js
- src/viewers/global-selection-hook.js
- src/views/VolumeView.js
- src/views/utils.js
This contains new features for the Viv core needed for #421
- Rescale the downsampled coordiante system to match the full resolution (and update `xSlice`, clipping planes etc. accordingly to use the new coordinate system)
- Handle onViewportLoad callbacks in the Viewers better (using `setTimeout` to make sure updates are propagated)
- Add an abort option for the `VolumeLayer` and `ImageLayer` so that `onViewportLoad` may be used to optimal effect
- Fix a bug in the loaders where the z size used to be necessary
> Small Features/Fixes for Viv Src

- avivator/src/components/Controller/components/Slicer.js
- avivator/src/components/Controller/components/VolumeButton.js
- avivator/src/components/Viewer.js
- avivator/src/constants.js
- avivator/src/source-info.js
- avivator/src/state.js
- avivator/src/utils.js
This should be the final PR - it reverts the slicing mechanism back to what it was previously with orthogonal slicing.  I also added my three favorite idr datasets for our demo and removed the H&E stain (was nice at first to show we can recognize it, but don't think it really adds anything).
- Update demo list with idr datasets and remove H&E example
- Revert slicing to only orthogonal clipping plane slicing.
> Slicing Reversion + New Demo Datasets

- CHANGELOG.md
- src/constants.ts
- src/index.js
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayerBase.js
- src/layers/XRLayer/XRLayer.js
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
Fixes #298.
I will add the choice to Avivator with the 3D stuff since Avivator is changing so much there.
- Add `interpolation` prop to all of the layers/components to allow for LINEAR vs. NEAREST filtering (called "interpolation")
> Allow for LINEAR/NEAREST Filtering Interpolation Choice

- src/constants.ts
- src/index.js
- src/layers/ImageLayer.js
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
- src/layers/MultiscaleImageLayer/utils.js
- src/layers/VolumeLayer/VolumeLayer.js
- src/layers/XR3DLayer/XR3DLayer.js
- src/layers/XRLayer/XRLayer.js
- src/viewers/PictureInPictureViewer.js
- src/viewers/SideBySideViewer.js
- src/viewers/VolumeViewer.js
Following up on #448 and #447 this removes the `interpolation` prop from publicly documented API's and only leaves it in the deck.gl props where necessary for the `MultiscaleImageLayer`.  I can just merge this if you'd rather see the full comaprison.
> Remove Auto Interpolation Prop (where possible)

- CHANGELOG.md
- package.json
- src/layers/XRLayer/XRLayer.js
Fixes #456
To test: https://vitessce-data.s3.us-east-1.amazonaws.com/demos/viv/feature_check/index.html
- Add checks for `LINEAR` + `FLOAT` support in WebGL1
> Fix Float + LINEAR checking

- CHANGELOG.md
- src/layers/VolumeLayer/VolumeLayer.js
- src/layers/VolumeLayer/utils.js
Mentioned during the Vitessce meeting, would be good to have a standard warning available for WebGL1.
- Add warning and `useWebGL1Warning` prop to `VolumeLayer`
> Add in-layer warning about WebGL1 to `VolumeLayer`.

- CHANGELOG.md
- src/layers/VolumeLayer/VolumeLayer.js
From the vitessce meeting.  This PR ensures the loading message re-appears after the resolution changes.
- Reset `VolumeLayer` state if resolution changes.
> Make sure loading message reappears if the resolution changes.

- CHANGELOG.md
- src/layers/ImageLayer.js
- src/layers/VolumeLayer/VolumeLayer.js
If more than one prop changes at a time, our current prop diffing mechanism only picks up one of the diffs.
- Don't use `changeFlags` for `updateState` prop diffing.
> Remove usage of `changeFlags` for `updateState` prop diffing

- CHANGELOG.md
- src/loaders/tiff/lib/utils.ts
- src/loaders/tiff/ome-tiff.ts
- src/loaders/utils.ts
- src/loaders/zarr/lib/utils.ts
Fixes #384
- Add ` guessTileSize` checker for TIFF pyramids
> `guessTileSize` for OME-TIFF loader

- CHANGELOG.md
- src/loaders/tiff/index.ts
- src/loaders/tiff/lib/Pool.ts
- src/loaders/tiff/lib/proxies.ts
- src/loaders/tiff/ome-tiff.ts
- src/loaders/tiff/pixel-source.ts
- tests/loaders/tiff-lib.spec.js
This is my mistake. The proxies are applied to the `GeoTIFF` source, and `readRasters` is a method on the _derived_ `GeoTIFFImage` object, so the proxied method with the decoder pool is never called.
It would be nice if you could configure a pool as an option on the _source_ `GeoTIFF` object, rather than needing to pass the `pool` and `tiff` around in unison. I tried to get this working with Proxies, but ran into a bit of a wall sadly. 
The fix is just to add `pool` as an optional constructor argument on the `TiffPixelSource`. 
Another option would be to wrap the return of a `pyramidIndexer` with a proxy, but this seems a bit overly complicated...
```javascript
let pyramidIndexer: OmeTiffIndexer;
if (SubIFDs) {
// Image is >= Bioformats 6.0 and resolutions are stored using SubIFDs.
levels …
```
> Restore decoder pool behavior; add `Pool` to `TiffPixelSource`

- CHANGELOG.md
- avivator/src/hooks.js
While looking for sample data for #474 I noticed that interleaved RGB handling in Avivator had broken so this PR fixes that.
- Match selections to number of channels created in Avivator.
> Fix Interleaved RGB Handling In Avivator

- CHANGELOG.md
- test.sh
We were getting a `./test.sh: line 9: [: missing `]'` warning previously.
> Fix Changelog Check.

- CHANGELOG.md
- src/layers/XRLayer/shader-modules/channel-intensity.glsl
Fixes #490
This maintains the channel color and doesn't use the maximum-value HSV equivalent.
Usual behavior with `rgb(0,255,0)`.
New behavior with `rgb(0,128,0)`.
- Maintain the value of the channel color in HSV when applying intensity
> Maintain the value of the channel color in HSV when applying intensity

- CHANGELOG.md
- package.json
Fixes #486 
We use the final bundle (`dist/viv.es.js`) with `documentation.js`'s `--document-exports` to generated our documentation. Something about Vite's JSX transform strips the comments from the final bundle, meaning there is nothing in `dist/viv.es.js` to autogenerate documentation.
Fortunately this issue is isolated to all files with `.jsx` extensions, and the only thing in each of those files that is exported is a React Component. This PR just adds `src/**/*.jsx` to the `npm run docs` script, telling `documentation.js` to both look at `dist/viv.es.js` as well as the source code with `.jsx` extensions when generating our docs.
> fix: restore React component documentation

- CHANGELOG.md
- avivator/src/components/Controller/components/VolumeButton.jsx
- avivator/src/utils.js
- src/layers/VolumeLayer/utils.js
@keller-mark raised this issue with some data (not public).  We should have been checking texture dimensions against the general standard limit of 2048 (some browsers/computers go larger but then there is the question of how practical downloading so much data is).
- Fix selection bug for thin volumes in channel stats
- Create checks against 1-depth volumes and those too large in the downsampled resolutions dropdown for volumes
- Ensure selections are valid within the layer utils (i.e the same bug as the first point)
> Better Handling of Thin 3D Volumes

- CHANGELOG.md
- avivator/empty-fs.js
- package-lock.json
- package.json
- rollup.config.test.js
- src/loaders/tiff/index.ts
- vite.config.js
Uses tagged release of `ilan-gold/geotiff.js` https://github.com/ilan-gold/geotiff.js/tree/viv. Removes need for `empty-fs.js` in vite config.
> Use viv-0.0.1 geotiff release

- CHANGELOG.md
- package.json
Similar to #486, the docs for the loaders regressed as well: http://viv.gehlenborglab.org/#loadometiff
- Add check for `src/loaders/**/*.ts ` to the `documentation` cli
> Fix `loaders` docs.

- CHANGELOG.md
- package-lock.json
- package.json
- src/loaders/tiff/ome-tiff.ts
Fixes #303 (I think)
- Upgrade Vite to `~2.5.4`
> Upgrade Vite

- CHANGELOG.md
- src/viewers/PictureInPictureViewer.jsx
- src/viewers/SideBySideViewer.jsx
- src/viewers/VivViewer.jsx
Fixes #503
- Add `deckProps` prop to viewer components
- Remove `glOptions` prop (which can be set via `deckProps`)
> Add general `deckProps` prop to Viewer components

- CHANGELOG.md
- avivator/src/utils.js
Keeps previous behavior, but now also tries to load multiscale OME-NGFF if loading bioformats fails. 
You can test this PR by loading the sub-resolution of the current Zarr example, which adheres to the OME-NGFF (v0.2) spec. It's important to note that the latest NGFF (v0.3) spec does not require there to be `omero` metadata, which is relied on here to fill in channel names, and also allows for non 5D images. Additionally rendering information from the omero metadata is ignored.
- http://localhost:3000/?image_url=https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr
- http://localhost:3000/?image_url=https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001251.zarr
You can try more links from here: https://www.openmicroscopy.org/2020/11/04/zarr-data.html
> feat(Avivator): add basic ome-ngff support

- .gitignore
- CHANGELOG.md
- avivator/src/utils.js
- package-lock.json
- package.json
- src/loaders/zarr/lib/utils.ts
- src/loaders/zarr/ome-zarr.ts
This pull request adds support for OME-NGFF v0.3 images:
- bump zarr.js to get support for "/" as a dimension separator 
- use multiscales[].axes to get the dimension ordering if available
- fix the catch statement in avivator
To try it, open https://minio-dev.openmicroscopy.org/idr/v0.3/idr0062-blin-nuclearsegmentation/6001240.zarr in avivator
> Use OME-Zarr multiscales[].axes

- CHANGELOG.md
- avivator/src/components/Snackbars/SnackbarAlerts.jsx
- tutorial/README.md
I noticed (a) our snackbar for `offsets.json` was lacking a working URL and (b) the documentation could be updated slightly to include both a clearer section and a link to your web app.
- Update docs to include link to indexing web app and make section heading clear for indexed TIFF
- Fix snackbar URL
> Update TIFF Offsets Snackbar

- CHANGELOG.md
- src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js
Becuase the `onViewportLoad` call back is passed to the background layer, it can be called before the actual layer loads.  This only became noticeable once we upgraded to deck.gl 8.6 since the whole layer no longer clears on selection changes.
- Set `onViewportLoad` to `null` for background layer.
> Fix `onViewportLoad` callback for `MultiscaleImageLayer`

- CHANGELOG.md
- README.md
Fixes #542 -- will need to rebuild site.
> doc(README): use full URLs for linked images in README

- src/loaders/tiff/index.ts
Changes introduced in #551 are actually still breaking because the return type of `loadOmeTiff` is widened to a union. TypeScript will not compile as it stands. 
This PR uses [function overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) to declare the return type based on the arguments. This will ensure that #551 is not a breaking change, and provide nicer use of the function in TS.
> Fix TS for multi-image OME-TIFF

- CHANGELOG.md
- avivator/src/Avivator.jsx
- avivator/src/components/Controller/Controller.jsx
- avivator/src/components/Controller/components/AddChannel.jsx
- avivator/src/components/Controller/components/CameraOptions.jsx
- avivator/src/components/Controller/components/ChannelController.jsx
- avivator/src/components/Controller/components/GlobalSelectionSlider.jsx
- avivator/src/components/Controller/components/Menu.jsx
- avivator/src/components/Controller/components/Slicer.jsx
- avivator/src/components/Controller/components/VolumeButton.jsx
- avivator/src/components/Footer.jsx
- avivator/src/components/Viewer.jsx
- avivator/src/hooks.js
- avivator/src/state.js
- avivator/src/utils.js
- src/loaders/tiff/index.ts
- src/loaders/tiff/lib/indexers.ts
- src/loaders/tiff/ome-tiff.ts
- tests/loaders/ome-tiff.spec.js
Fixes #344 - see https://github.com/hms-dbmi/viv/discussions/546#discussioncomment-1782740 as well
- Allow `loadOmeTiff` to return an array `Promise<{ data: TiffPixelSource[], metadata: ImageMeta }>[]` of images.  This should not be a breaking change because I added the `useMultiImage` flag and set it to `false`.   In a future major release, we can set this to `true` by default (or just get rid of it).
- Update Avivator to handle an array of images.  The behavior is that if the "Image" changes, Avivator completely resets, including the 3D mode
> Multiple OME Images

- CHANGELOG.md
- src/types.ts
Latest types don't have the desired effect (tested in Vizarr). The `Viv` type refines only the properties that are defined on the JSdoc `LayerProps` for the the corresponding layer. This PR refactors the types and conditionally adds the optional extension props if `loader` is defined for the layerprops.
> Fix Viv 0.12 types

- CHANGELOG.md
- avivator/src/components/Controller/Controller.jsx
- avivator/src/components/Controller/components/GlobalSelectionSlider.jsx
#540 Fixed nothing in reality.  So I have just removed the viewing rendering settings from the callback and will ask deck.gl what is going on.
- Move channel setting state-setting outside on `onViewportLoad`
> Fix Selection Callbacks

- CHANGELOG.md
- avivator/src/components/Controller/components/AddChannel.jsx
- avivator/src/components/Controller/components/VolumeButton.jsx
Following up on #555 
- Remove channel-settings setting from `onViewportLoad` callback
> Fix "Add Channel" and "Show Volume" buttons

- CHANGELOG.md
- src/loaders/tiff/lib/indexers.ts
Fixes a small bug where we offset uniformly by the first image's dimensions but in reality we need to offset by whatever the previous images' dimensions were.
- FIx OME-TIFF muti-image indexing.
> Fix Multi-Image Indexing

- CHANGELOG.md
- package-lock.json
- package.json
Toward https://github.com/hubmapconsortium/portal-ui/issues/2345
- Upgrade geotiff with fix
> Upgrade geotiff to solve 416 issue

- CHANGELOG.md
- vite.config.js
Fixes #561 
The `@vite/plugin-react` plugin applies React's automatic jsx runtime (which ended up being exported in the final bundle). This PR disables `@vite/plugin-react` for `npm run build`, deferring to esbuild _alone_ to apply the JSX transformation (`React.createElement`).
> fix: disable vite/plugin-react for ESM build

- CHANGELOG.md
- package-lock.json
- package.json
Fixes https://github.com/hms-dbmi/viv/discussions/546#discussioncomment-2025372.  I introduced this with #563 and this should resolve it.
- Upgrade geotiff fork to 0.0.4 to fix file size check
> Upgrade Geotiff to Fix File Size Check

- CHANGELOG.md
- avivator/src/components/Controller/components/ChannelController.jsx
- src/layers/XRLayer/XRLayer.js
Fixes https://github.com/hms-dbmi/viv/issues/591#issuecomment-1119098351
- Make sure to actually use `cast` function in `XRLayer` when it is returned with the value for a given `dtype`
> Fix Casting Bug for `Float64`

- CHANGELOG.md
- src/viewers/VivViewer.jsx
See #605
- Support passing in additional layers to VivViewer through deckProps
> Support passing in additional layers to VivViewer through deckProps

- CHANGELOG.md
- README.md
- package.json
Adds a `postversion` script to `package.json` to automate the release steps. Now the release workflow should be:
```bash
git checkout master && git pull
pnpm version [major | minor | patch | prepatch]
git push --follow-tags
```
> feat: add postversion script

- CHANGELOG.md
- packages/loaders/src/tiff/index.ts
Updates JSDoc for `loadMultiTiff` and adds additional `header` and `name` options to `MultiTiffOptions`. Also removes name inference (which incorrectly used negative indexing), the `opts.name` should be preferred to provide an explicit name for the image if desired.
> chore: update `loadMultiTiff` docs and remove name inference 

- CHANGELOG.md
- package.json
The `postversion` script modified the commit history _after_ the tagged commit was made. This PR fixes the release behavior so that the tagged commit has the latest changes.
> fix: use `version` script instead of `postversion` for creating tagged release commits

- CHANGELOG.md
- packages/layers/src/multiscale-image-layer/multiscale-image-layer.js
In deck.gl 8.8 this must have changed? Not sure what happened here...
- Use new `getTileData` arguments.
> (fix): `getTileData` args changed

- CHANGELOG.md
- sites/avivator/src/utils.js
avivator does not work for ome-tiff in private s3. 
change in utils.js, check http code !==200 instead of ===404
this is related to #634 @jkh1
> avivator images in private s3 presigned url

- CHANGELOG.md
- packages/viewers/src/VivViewer.jsx
- sites/avivator/src/utils.js
Discovered during release testing - the issue was also seen in #632 
- Use `index` instead of `z` directly on the tile in the `onHover` function.
> (bug): Fix `onHover` in `VivViewer`

- CHANGELOG.md
- packages/loaders/src/tiff/index.ts
- packages/loaders/src/tiff/lib/utils.ts
- packages/loaders/src/tiff/multi-tiff.ts
- packages/loaders/tests/multi-tiff.spec.js
- sites/avivator/src/utils.js
See #636 
- Adds support for loading stacked TIFFs to the MultiTIFF loader and to Avivator.
> Stacked tiff

- CHANGELOG.md
- packages/loaders/src/tiff/index.ts
- packages/loaders/tests/multi-tiff.spec.js
- packages/loaders/tests/ome-tiff.spec.js
Fixes #637
- Adds support for loading image files using GeoTIFF's `fromFile` method if the url is prefixed with `file://`.
> Adds support for loading local TIFFs using GeoTIFF's fromFile loader.

- .github/workflows/test_and_publish.yml
- CHANGELOG.md
see https://github.com/hms-dbmi/viv/actions/runs/3656876866 for failure
> (fix): ci pinned to ubuntu 20

- CHANGELOG.md
- sites/avivator/src/components/Controller/Controller.jsx
- sites/avivator/src/components/Controller/components/AddChannel.jsx
- sites/avivator/src/hooks.js
Fixes #657 
- Don't rely on the default color palette or the metadata for determining colors
> (fix): allow for OME-TIFF with lots fo channels but no default color

- CHANGELOG.md
- packages/loaders/src/zarr/lib/utils.ts
- packages/loaders/src/zarr/ome-zarr.ts
Fixes #586
- Allow for loading `viv` `labels` from new `axes` metadata to support v0.4
> (feat): updated `labels` to work with new `axis` for omengff v0.4

- CHANGELOG.md
- packages/layers/src/xr-layer/utils.js
- packages/layers/src/xr-layer/xr-layer.js
- packages/layers/tests/utils.spec.js
We noticed that image pyramids for `Float64` data had stopped working in HuBMAP and it turns out there was a reversion here: https://github.com/hms-dbmi/viv/pull/606/files#diff-2c110f17c1fdf417f10e305da452bca1673357b88d8815dd47cd7698d81a5424
This is a little bit concerning considering the size of that PR but I made another pass at it and didn't notice anything else.  cc @manzt 
- Revert the `Float64` fix reversion
> (fix): Revert `Float64` Reversion

- CHANGELOG.md
- packages/views/src/OverviewView.js
Fixes #645
- Clicking on overview was not centering main viewer. It seems that there's contradiction in deck.gl documentation:
https://deck.gl/docs/api-reference/core/controller. Specifically, `Controller` class is only accepting `props` without the `Viewstate`. Passing `Viewstate` to `super` instead of props was causing the lack of response on mouse events, as `props` contain, among others, `EventManager` which subscribes to user events.
- Fixed the issue where clicking on overview window did not center the main viewer accordingly
> fix: Fixing overview click event not firing

- .github/workflows/test_and_publish.yml
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
> chore: Bump gl to latest and move to Node.js 18 in CI

- CHANGELOG.md
- packages/loaders/package.json
- packages/loaders/src/zarr/pixel-source.ts
- pnpm-lock.yaml
An alternative to #698. This removes the code paths for importing from ZarrJS in the `ZarrPixelSource`. It should be straightforward to introduce an adapter for `zarrita` to support the `ZarrSource` interface. 
```javascript
import { FetchStore, open, get } from "zarrita";
function zarrSourceAdapter(arr) {
return {
dtype: convertToV2DataType(arr.dtype),
shape: arr.shape,
chunks: arr.chunks,
getRaw: (selection, { storeOptions }) => get(arr, selection, { opts: storeOptions }),
}
}
let store = new FetchStore("http://localhost:8080/data.zarr");
let arr = await open(store, { kind: "array" });
let pixelSource = new ZarrPixelSource(zarrSourceAdapter(arr), ...);
```
Aligning the TypeScript types for these libraries is really going to be a pain. Some of the typing is really wack in ZarrJS, and the …
> feat(loaders): Introduce more minimal required Zarr interface

- CHANGELOG.md
- packages/loaders/package.json
- packages/loaders/src/omexml.ts
- packages/loaders/src/utils.ts
- packages/loaders/tests/index.spec.js
- pnpm-lock.yaml
Removes `fast-xml-parser` dependency in favor of using [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) Web API.
All the examples and tests are passing, but I don't think Avivator makes use of much of the metadata. This is probably somewhere that snapshot testing could help us a bit. @keller-mark, I don't anticipate this to be a breaking change but maybe there is something I'm missing wrt what Vitessce relies on (if any) of the parsed and modified OME-XML metadata.
Fixes #
-
> feat(loaders): Drop `fast-xml-parser`

- CHANGELOG.md
- packages/loaders/package.json
- packages/loaders/src/omexml.ts
- packages/loaders/src/tiff/lib/indexers.ts
- packages/loaders/src/tiff/lib/utils.ts
- packages/loaders/src/tiff/ome-tiff.ts
- packages/loaders/src/utils.ts
- packages/loaders/src/zarr/lib/utils.ts
- pnpm-lock.yaml
Replaces TS types with `zod` definitions, for runtime validation. This way, if some expectation about types is broken, there will be a nicer error message in the console. 
This is important for handling #697
> feat: Validate expected OME-XML metadata

- CHANGELOG.md
- packages/layers/src/overview-layer.js
- packages/loaders/src/omexml.ts
- sites/docs/src/API_STRUCTURE.md
- sites/docs/src/SAMPLES.md
Addresses https://github.com/hms-dbmi/viv/issues/533#issuecomment-1009432218
- Add a default `extension` prop for `OverviewLayer`
> Clarify Docs on and Fix Extensions on `OverviewLayer`

- CHANGELOG.md
- packages/loaders/src/utils.ts
Fixes weird case in Firefox where XML-parsing breaks with a trailing null byte in XML string.
> fix(loaders): trim trailing `\u0000` in OME-XML string for Firefox compat

- CHANGELOG.md
- packages/loaders/src/omexml.ts
- sites/avivator/src/utils.js
Allows for `METADATA.ome.xml` to omit TiffData tags.
> fix(loaders): Allow optional TiffData in OME-XML

- .changeset/config.json
Keeps the current behavior of versioning viv with all sub packages together.
> chore: Set `fixed` versioning scheme

- .changeset/serious-plants-visit.md
- packages/loaders/src/omexml.ts
Closes #1296
Uses the `zod` validation to provide the default value.
- https://github.com/vitessce/vitessce/issues/1296
> feat(loaders): Set default PhysicalSizeUnit to µm

- .github/workflows/release.yml
- package.json
- scripts/version.mjs
The workflow used `pnpm version` which is a reserved command in `pnpm`, breaking the action. This PR just calls the node script for versioning directly in CI.
> fix: run versioning script directly in GH Action

- pnpm-lock.yaml
- sites/avivator/package.json
- sites/avivator/src/Avivator.jsx
- sites/avivator/src/hooks.js
- sites/avivator/src/index.jsx
We aren't doing anything sophisticated with routing in Avivator (besides pushing some state to the URL), which can be done without a library.
> feat(avivator): Drop react-router-dom

- .changeset/popular-steaks-end.md
- packages/loaders/src/omexml.ts
- packages/loaders/src/tiff/lib/indexers.ts
- packages/loaders/src/tiff/lib/utils.ts
- packages/loaders/src/tiff/multi-tiff.ts
- packages/loaders/src/tiff/multifile-ome-tiff.ts
- packages/loaders/src/tiff/singlefile-ome-tiff.ts
- packages/loaders/src/utils.ts
Extends on #740 
This release PR Viv's multifile OME-TIFF data-loading capabilities to multiscale TIFFs as well. The `loadOmeTiff` utility now recognizes and loads multiresolution images described in a `companion.ome` metadata file. 
The API stays the same for end users. Multifile OME-TIFFs are detected from URLs with path suffixes of `*companion.ome`.
```js
import { loadOmeTiff } from '@vivjs/loaders';
let loader = await loadOmeTiff("http://localhost:8080/data.companion.ome");
```
> feat: Support mutifile & multiscale OME-TIFF

- package.json
- pnpm-lock.yaml
I'd assumed that this dependency was somehow used in our test suite to mock WebGL but it doesn't appear like removing it causes any problems to CI or running tests locally. I say we remove it.
See:
- #828 
- #826 
cc: @xinaesthete
> chore: Remove gl devDependency

- pnpm-lock.yaml
- sites/avivator/package.json
- sites/avivator/src/components/Controller/Controller.jsx
- sites/avivator/src/components/Controller/components/AddChannel.jsx
- sites/avivator/src/components/Controller/components/CameraOptions.jsx
- sites/avivator/src/components/Controller/components/ChannelController.jsx
- sites/avivator/src/components/Controller/components/GlobalSelectionSlider.jsx
- sites/avivator/src/components/Controller/components/LensSelect.jsx
- sites/avivator/src/components/Controller/components/Menu.jsx
- sites/avivator/src/components/Controller/components/PanLockToggle.jsx
- sites/avivator/src/components/Controller/components/PictureInPictureToggle.jsx
- sites/avivator/src/components/Controller/components/RenderingModeSelect.jsx
- sites/avivator/src/components/Controller/components/SideBySideToggle.jsx
- sites/avivator/src/components/Controller/components/Slicer.jsx
- sites/avivator/src/components/Controller/components/VolumeButton.jsx
- sites/avivator/src/components/Controller/components/ZoomLockToggle.jsx
- sites/avivator/src/components/Footer.jsx
- sites/avivator/src/components/Snackbars/Snackbars.jsx
- sites/avivator/src/components/Viewer.jsx
- sites/avivator/src/hooks.js
- sites/avivator/src/state.js
Towards https://github.com/hms-dbmi/viv/issues/745#issuecomment-2484961710
https://zustand.docs.pmnd.rs/migrations/migrating-to-v5
- Migrate to `useShallow` hook where we used `shallow` before or where applicable (returning new references)
> (chore): upgrade zustand

- pnpm-lock.yaml
- sites/avivator/package.json
- sites/avivator/src/components/Controller/Controller.jsx
- sites/avivator/src/components/Controller/components/AddChannel.jsx
- sites/avivator/src/components/Controller/components/CameraOptions.jsx
- sites/avivator/src/components/Controller/components/ChannelController.jsx
- sites/avivator/src/components/Controller/components/ChannelOptions.jsx
- sites/avivator/src/components/Controller/components/ColorPalette.jsx
- sites/avivator/src/components/Controller/components/ColormapSelect.jsx
- sites/avivator/src/components/Controller/components/DropzoneButton.jsx
- sites/avivator/src/components/Controller/components/GlobalSelectionSlider.jsx
- sites/avivator/src/components/Controller/components/LensSelect.jsx
- sites/avivator/src/components/Controller/components/Menu.jsx
- sites/avivator/src/components/Controller/components/MenuTitle.jsx
- sites/avivator/src/components/Controller/components/PanLockToggle.jsx
- sites/avivator/src/components/Controller/components/PictureInPictureToggle.jsx
- sites/avivator/src/components/Controller/components/RenderingModeSelect.jsx
- sites/avivator/src/components/Controller/components/SideBySideToggle.jsx
- sites/avivator/src/components/Controller/components/Slicer.jsx
- sites/avivator/src/components/Controller/components/VolumeButton.jsx
- sites/avivator/src/components/Controller/components/ZoomLockToggle.jsx
- sites/avivator/src/components/Footer.jsx
- sites/avivator/src/components/RenderingModeSelect.jsx
- sites/avivator/src/components/Snackbars/SnackbarAlerts.jsx
- sites/avivator/src/components/Snackbars/Snackbars.jsx
- sites/avivator/src/index.jsx
For https://github.com/hms-dbmi/viv/issues/745#issuecomment-2484961710
- Upgrade Material UI to 6.x.x
> (chore): upgrade material ui

- .changeset/purple-bobcats-jog.md
- package.json
- packages/constants/src/index.ts
- sites/avivator/src/utils.js
Brings back support for signed integer data types (`Int8`, `Int16`, `Int32`).
http://localhost:5173/?image_url=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr/labels/0
Fixes #
-
> Fix typo in luma texture format names for signed integers

- .changeset/twelve-flowers-beam.md
- .github/workflows/ci.yml
- packages/constants/src/index.ts
Reverts accidental change introduced in #865. We should really use a TypeScript to help us with these kind of things.
> Fix typo in luma texture format for Float32Array (`r32float`)

- packages/loaders/src/tiff/index.ts
Fixes #881 (in so far as it gives a better warning)
This part of things is quite messy.  We probably can't remove this feature for multiple-tiff files, but the whole feature introduced the ability to visualize multi-channel tiff files (my mistake) unintentionally to Avivator, when it should have been disallowed.  At least now, we can provide a clearer warning for when someone tries to visualize something that won't even appear on screen.
- Add a check on `SamplesPerPixel` in the `multi-tiff` lodare
> (fix): disallow multiple samples per pixel in multi-channel tiff
